const ACTIONS = {
  GET_POKEMON_LIST: 'GET_POKEMON_LIST',
  GET_POKEMON: 'GET_POKEMON',
  GET_FAVORITE: 'GET_FAVORITE',
  DEL_FAVORITE: 'DEL_FAVORITE',
  ADD_FAVORITE: 'ADD_FAVORITE',
};

export default ACTIONS;
